lesson_2
alextitov1/learn_python pull request #3
Opened 2023-09-04 03:02 UTC by alextitov1

2023-09-04 03:06 UTC, alextitov1 commented on telegram_bot/bot.py
> +    planet.compute()
@techogleb, что здесь происходит, я не понимаю? (решение предложил копайлот)
можно ссылку на статью, а лучше книгу

2023-09-04 03:06 UTC, alextitov1 commented on telegram_bot/bot.py
> +def planet_constellation(update, context):
для чего здесь переменная context?

2023-09-04 03:08 UTC, alextitov1 commented on telegram_bot/bot.py
> +                   callback=planet_constellation))
не понятно, что за тип данных callback и почему присваивается имя функции без аргументов

2023-09-07 13:09 UTC, technogleb requested changes
Коменты там, где есть вопросы или замечания. В остальных местах все ок.

2023-09-07 13:09 UTC, technogleb commented on lesson_2/1_if1.py
> +
Так как ты внутри каждого условного оператора делаешь возврат, то elif тут излишни. Можно написать только if-ы.

2023-09-07 13:09 UTC, technogleb commented on lesson_2/1_if1.py
> +
```python
def define_activity(age):
     if 0 <= age <= 6:
         return "You're a kindergartner"
     if 7 <= age <= 17:
         return "You're a schoolboy"
     if 18 <= age <= 23:
         return "You're a student"
     if 24 <= age <= 65:
         return "You're a worker"
     if 66 <= age <= 100:
         return "You're a retiree"
     return "You're probably dead"
```

2023-09-07 13:09 UTC, technogleb commented on lesson_2/2_if2.py
> +        return 'Something went wrong'
Аналогично с elif.

2023-09-07 13:09 UTC, technogleb commented on lesson_2/3_for.py
> +    ava_salles = total_salles / len(SALLES)
Среднее кол-во продаж всех товаров определяется как сумма всех продаж по всем телефонам делить на количество продаж по всем телефонам. А ты, написав len(sales), делишь на количество телефонов.

2023-09-07 13:09 UTC, technogleb commented on telegram_bot/bot.py
>  from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
Согласно PEP8 (https://peps.python.org/pep-0008/#imports) мы упорядочиваем импорты в питоне по следующему правилу -  стандартная библиотека, пустая строка, site-packages (то, что ты установил через pip), пустая строка, собственные импорты (то есть импорты своих же модулей из этого же проекта).

```python
import os
import sys
import logging

import ephem
from doting import load_dotenv
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
```

2023-09-07 13:09 UTC, technogleb commented on telegram_bot/bot.py
> +def planet_constellation(update, context):
context нужен для того, чтобы получать некий "контекст", в котором происходит взаимодействие с телеграмом. Например - там присутствуют объекты bot_data, chat_data, user_data, куда можно складывать какую-то информацию по боту, чату или юзеру, соответственно.

Например, ты хочешь для каждого пользователя иметь какую-то доп инфу , чтобы позже отвечать ему не с нуля, а используя некий контекст. Вот такую штуку можно положить в user_data. 

```python
context.user_data['key'] = 'some_data'
```

2023-09-07 13:09 UTC, technogleb commented on telegram_bot/bot.py
> +def planet_constellation(update, context):
Например, наш бот, через который ты отправляешь мне сообщения на проверку, хранит информацию о двоих ДЗ в контексте.

2023-09-07 13:09 UTC, technogleb commented on telegram_bot/bot.py
> +    planet.compute()
Так, начну с 42 строчки. 
planet = getattr(ephem, planet_name) берет модуль ephem, достает из него аттрибут с именем planet_name и кладет в переменную planet.

Например, `planet = getattr(ephem, 'Mars')` вернет класс Mars.

Далее, в 43 строчек мы создаем экземпляр класса, то есть пишем Mars() (то есть мы достали только класс, а еще нужно сделать его экземпляр)

В 44 строчке вызывается метод .compute(), который для заданного времени вычисляет все звездные координаты планеты. Если время не передано, как в нашем случае, вычисляет для текущего времени. Эти координаты хранятся в полях класса, таких как earth_distance или sun_distance, например.

Например, следующий код достанет из модуля ephem планету Jupiter, и посчитает расстояние до земли, которое имела планета на момент "2023-01-01".
```python
Jupiter = getattr(ephem, 'Jupiter')
jup = Jupiter()
jup.compute("2023-01-01")
jup.earth_distance
```

compute нам надо вызывать для того, чтобы функция constellation в 45 строчке могла понять, в каком созвездии находится планета.

2023-09-07 13:09 UTC, technogleb commented on telegram_bot/bot.py
> +                   callback=planet_constellation))
Тут ты добавляешь в бота новую команду "planet". Как боту понять что с этой командой делать? Ну он тебе как бы говорит - "ты напиши для меня функцию, которую я буду вызывать каждый раз, когда передана команда planet, и не забудь, чтобы аргументами функции были объекты update и context, чтобы я знал, что с ней делать. Эту функцию передай в параметр callback"

Собственно во фразе "которую я буду вызывать каждый раз, когда передана команда planet" содержится ответ, почему передаем мы именно саму функцию, а не то, что она возвращает. 
Фреймворк просит от тебя инструмент, который он будет использовать, то есть объект типа функция. Если мы передадим с аргументами, то мы тупо вызовем функцию и передадим то, что она возвращает, а не саму функцию.

2023-09-10 01:42 UTC, alextitov1 commented on telegram_bot/bot.py
> +def planet_constellation(update, context):
@technogleb перефразирую вопрос. Переменная `context` в коде функции явно ни куда не применяется (даже IDE её подсвечивает как не используемая), но если её убрать то функция ломается. Вопрос - где применяется или какой объект использует переменную `context`?

2023-09-19 10:35 UTC, merged